#!/usr/bin/env python3
"""Replace generic RM content with exam-specific content for all 29 exams."""
import re

with open('/home/hal9000/Projects/Medscaner_prep/index.html', 'r', encoding='utf-8') as f:
    content = f.read()

def make_entry(key, title, agend, anam, triag, prot):
    parts = [f"{key}: `<b>{title} — TRIAGEM E PROTOCOLO</b><br><br>"]
    parts.append("<b>1. INFORMAÇÕES PARA AGENDAMENTO:</b><br>")
    for x in agend:
        parts.append(f"• {x}<br>")
    parts.append("<br><b>2. PERGUNTAS PARA ANAMNESE (Enfermagem):</b><br>")
    for x in anam:
        parts.append(f"• {x}<br>")
    parts.append("<br><b>3. TRIAGEM DE PATOLOGIAS (Enfermagem):</b><br>")
    for x in triag:
        parts.append(f"• {x}<br>")
    parts.append("<br><b>4. RECOMENDAÇÕES AO TÉCNICO (Protocolo):</b><br>")
    for x in prot:
        parts.append(f"• {x}<br>")
    parts.append("`,")
    return ''.join(parts)

def replace_exam_entry(data, key, new_entry):
    """Replace the entry for a given key with new content."""
    # Find the key at the start of a line
    pattern = r'\n\s+' + re.escape(key) + r':\s*`[^`]*`'
    m = re.search(pattern, data)
    if not m:
        print(f"  WARNING: {key} not found")
        return data
    old = m.group()
    print(f"  {key}: replacing {len(old)} chars with {len(new_entry)} chars")
    return data[:m.start()] + '\n    ' + new_entry + data[m.end():]

# Define all 29 exam-specific entries
exams = {}

exams['abdome'] = make_entry('abdome', 'RESSONÂNCIA MAGNÉTICA DE ABDOME',
    ['Jejum de 4–6 horas antes do contraste (diretriz ACR 2024)',
     'Perguntar sobre implantes metálico-eletrônicos (bomba de insulina, neuroestimulador) — contraindicação relativa',
     'Informar tempo médio de exame: 30–45 minutos',
     'Perguntar sobre claustrofobia — RM aberta ou sedação podem ser necessárias',
     'Não é necessário suspender medicações habituais',
     'Confirmar ausência de marca-passo convencional (contraindicação absoluta)',
     'Avaliar função renal (creatinina) se uso de gadolínio planejado (risco de NSF)',
     'Perguntar sobre nefropatia ou transplante renal prévio',
     'Orientar que gel de ultrassom pode ser usado na superfície abdominal'],
    ['Qual a indicação clínica principal? (lesão focal hepática, pancreática, adrenal?)',
     'Hepatopatia conhecida ou ferritina elevada? (sobrecarga hepática)',
     'História de doença renal ou diálise?',
     'Cirurgias abdominais prévias? (adesões podem limitar avaliação)',
     'Sintomas: dor, icterícia, perda de peso, alteração do hábito intestinal?',
     'Reação prévia a gadolínio?'],
    ['Lesões hepáticas focais — hemangioma, adenoma, carcinoma hepatocelular (CHC), metástases',
     'Esteatose hepática — quantificação com espectroscopia RM quando disponível',
     'Lesões pancreáticas — neoplasia sólida vs. cística (IPMN, serosa), pancreatite crônica',
     'Lesões adrenais — adenoma (wash-out), feocromocitoma, metástases',
     'Vias biliares — colangite, dilatação, estenoses obstrutivas',
     'Linfonodomegalias retroperitoneais e mesentéricas, ascite'],
    ['Bobina phased-array sobre o abdome + bobina corporal',
     'Sequências: T2 HASTE/coronal, T2 SPAIR/STIR, T1 Dixon (in-phase/opposed-phase), difusão (DWI b=50,400–800)',
     'Contraste dinâmico: gadolínio 0,1 mmol/kg, fase arterial tardia (15–20s), portal (60–70s), hepática (180s)',
     'Avaliar hepatoesplenomegalia, ascite, adenopatias',
     'Cortes axiais e coronais oblíquos, espessura ≤5mm para lesões pequenas'])

exams['angiorm_arterial_cranio'] = make_entry('angiorm_arterial_cranio', 'RESSONÂNCIA MAGNÉTICA DE ANGIORM ARTERIAL DE CRÂNIO',
    ['Sem contraste: jejum não é necessário',
     'Com contraste: jejum de 4 horas (prevenir náuseas)',
     'Perguntar sobre implantes metálicos intracranianos (stents, coils, clipes de aneurisma)',
     'Claustrofobia — RM de campo aberto pode ser necessária',
     'Informar tempo de exame: 20–35 minutos',
     'Confirmar ausência de marca-passo convencional (contraindicação absoluta)',
     'Avaliar função renal se gadolínio será usado (NSF — fibrose sistêmica nefrogênica)',
     'Perguntar sobre reações anteriores a agentes de contraste paramagnético'],
    ['Qual a indicação? (aneurisma, MAV, estenose, AVC isquêmico?)',
     'História de aneurisma cerebral ou sangramento subaracnóideo?',
     'Trazer exames anteriores para comparação',
     'Hipertensão arterial, diabetes, dislipidemia (fatores de risco vascular)?',
     'AVC prévia ou AIT? Qual território vascular?',
     'Procedimentos endovasculares prévios (stent, coil)?'],
    ['Aneurismas intracranianos — localização (ACO, ACM, ACoA), tamanho, morfologia (sacular vs. fusiforme)',
     'Malformações arteriovenosas (MAV) — nidus, drenagem venosa, fístula dural',
     'Estenose ou oclusão arterial — ateromatose, dissecção, vasculite',
     'Vasoespasmo pós-hemorrágico — avaliar com TOF ou contraste',
     'Stroke isquêmico agudo — penumbra isquêmica, core isquêmico (DWI/FLAIR mismatch)',
     'Developmental venous anomalies (DVA) — malformações venosas developmentais'],
    ['3D TOF (time-of-flight) sem contraste como base — evalua artérias do círculo de Willis',
     '3D contraste (MRA) com gadolínio 0,1 mmol/kg — bobina phased-array de crânio',
     'Sequência 3D T1-MPRAGE pós-contraste para parede vascular e trombose',
     'Incluir artérias: carótidas internas, ACM, ACA, ACP, basilare, vertebrais',
     'Resolução espacial alta: voxel ≤0,5mm, reconstruções MIP e MPVAR',
     'Avaliar simultaneamente parênquima (DWI, FLAIR) para excluir processo isquêmico'])

exams['angiorm_venosa_cranio'] = make_entry('angiorm_venosa_cranio', 'RESSONÂNCIA MAGNÉTICA DE ANGIORM VENOSA DE CRÂNIO',
    ['Sem contraste: jejum não é necessário',
     'Com contraste: jejum de 4 horas',
     'Avaliar função renal (creatinina) se uso de gadolínio',
     'Perguntar sobre trombose venosa prévia ou fatores de risco (trombofilia, anticoncepcionais)',
     'Informar tempo de exame: 20–35 minutos',
     'Claustrofobia — explicar que a cabeça fica dentro do imã',
     'Confirmar ausência de marca-passo convencional, DIU de cobre é compatível',
     'Alertar que contraste será injetado para opacificar as veias'],
    ['Qual a indicação? (cefaleia, trombose venosa cerebral, avaliação de seios venosos?)',
     'Cefaleia de início recente ou com padrão atípico?',
     'Histórico de trombose venosa profunda ou superficial?',
     'Episódios de convulsões, déficit neurológico focal?',
     'Uso de anticoncepcionais orais, terapia hormonal (risco de TVC)?',
     'Neoplasia ocultada (síndrome de Trousseau)?',
     'Infecção sinusal recente ou mastoidite (risco de trombose de seio lateral)?'],
    ['Trombose venosa cerebral (TVC) — seios sagital superior, lateral, reto, jugular',
     'Vedadores venosos (seios) — aplasia ou hipoplasia, causa de HTIC benigna',
     'Mass effect sobre seios venosos por processos expansivos',
     'Tromboflebite intracraniana — extensão de processo infeccioso',
     'Colaterais venosos desenvolvidos — resultado de hipertensão intracraniana',
     'Infartos venosos — padrão hemorrágico cortical, edema vasogênico'],
    ['2D/3D TOF venografia ou contraste com gadolínio 0,1 mmol/kg',
     '3D T1 + saturação de gordura pós-contraste para avaliar trombose vs. recanalização',
     'Sequências parenquimatosas: FLAIR, DWI para excluir infarto venoso',
     'Incluir seios: sagital superior, lateral, reto, jugular',
     'Reconstruções MIP e multiplanar para avaliar continuidade venosa',
     'Avaliar edema, hemorragia ou infarto venoso associado'])

exams['arcos_costais'] = make_entry('arcos_costais', 'RESSONÂNCIA MAGNÉTICA DE ARCOS COSTAIS',
    ['Não é necessário jejum',
     'Perguntar sobre dor torácica intensa — avaliar capacidade de imobilidade durante exame',
     'Informar tempo de exame: 25–40 minutos por hemitórax',
     'Claustrofobia geralmente moderada para esta região',
     'Confirmar ausência de marca-passo ou dispositivos eletrônicos',
     'Avaliar função renal se contraste será usado (necessário para neoplasia)',
     'Perguntar sobre fraturas costais recentes ou em consolidação',
     'Orientar uso de roupas sem elementos metálicos no tronco'],
    ['Qual a indicação? (trauma, dor, suspeita de neoplasia, fratura por estresse?)',
     'História de trauma torácico recente ou antigo?',
     'Dor em ponto específico ou difusa? Piora com respiração profunda?',
     'Febre ou sinais de infecção (osteomielite)?',
     'Neoplasia conhecida de mama, pulmão ou outra localização?',
     'Sintomas constitucionais: perda de peso, sudorese noturna?',
     'Bilateral ou unilateral? (neoplasia geralmente unilateral)'],
    ['Fraturas de costelas — consolidação em fase tardia, calo ósseo, pseudartrose',
     'Neoplasia costal — plasmocitoma, metástases, osteossarcoma, condrossarcoma',
     'Osteomielite — edema medular, realce após contraste, sequestro',
     'Doença de Paget torácica — cortical espessada, padrão mosqueado',
     'Biópsia prévia — avaliar residual tumoral ou infecção',
     'Derrame pleural associado, espessamento pleural'],
    ['Bobina de superfície phased-array sobre a região torácica',
     'Sequências: T1, T2 SPAIR/STIR (suprime gordura), difusão (DWI) para caracterizar lesão',
     'Contraste dinâmico com gadolínio 0,1 mmol/kg para neoplasia',
     'Avaliar todas as costelas visíveis (geralmente 3ª a 10ª), bilateral se necessário',
     'Cortes axiais e coronais oblíquos, incluir arcada costal completa',
     'Atenuar artefatos de movimento respiratório com gating ou apneia'])

exams['articulacao_temporomandibular'] = make_entry('articulacao_temporomandibular', 'RESSONÂNCIA MAGNÉTICA DE ARTICULAÇÃO TEMPORO-MANDIBULAR',
    ['Não é necessário jejum',
     'Tempo de exame: 30–40 minutos (bilateral com mandíbula fechada e aberta)',
     'Claustrofobia relevante — a cabeça fica dentro do imã',
     'Confirmar ausência de fragmentos metálicos intraorais (amalgama dentária — artefactos)',
     'Informar que o exame inclui manobras de abertura mandibular (dispositivo de oclusão)',
     'Perguntar sobre dificuldade prévia para abrir a boca (limitação funcional)',
     'Dispositivos ortodônticos — avaliar se removíveis antes do exame',
     'Implantes cocleares — informar para verificar compatibilidade com RM'],
    ['Qual a indicação? (dor, deslocamento de disco, artrite, crepitação?)',
     'Uni ou bilateral? (artrite reumatoide tipicamente bilateral)',
     'Ruídos articulares (click, crepitação)? Desde quando?',
     'Limitação de abertura de boca? (normal ~40mm interincisal)',
     'Dor articular espontânea ou à mastigação?',
     'Histórico de bruxismo, apertamento dentário?',
     'Trauma prévia na região mentoniana ou ATM?',
     'Doenças reumatológicas associadas (artrite reumatoide, lúpus)?'],
    ['Deslocamento de disco com redução (DDCR) — disco deslocado anteriormente, redução na abertura',
     'Deslocamento de disco sem redução (DDSR) — limitação de abertura, desvio para o lado afetado',
     'Osteoartrite da ATM — erosões condilares, osteófitos, edema da medula óssea',
     'Artrite inflamatória — sinovite, derrame articular, realce sinovial',
     'Anquilose da ATM — ausência de espaço articular, fusão óssea',
     'Neoplasia — massa de partes moles na fossa mandibular ou ao redor da articulação'],
    ['Bobina de superfície ou bobina de mandíbula dedicada',
     'Sequências closed-mouth: T1 (anatomia), PD ou T2 (edema/efusão), GRE para disco',
     'Sequências open-mouth: T1 e GRE para avaliar redução do disco',
     'Contraste com gadolínio se suspeita de sinovite, artrite ou neoplasia',
     'Cortes coronais oblíquos e sagitais oblíquos perpendiculares ao côndilo',
     'Usar dispositivo de oclusão para garantir posição reprodutível'])

exams['bacia'] = make_entry('bacia', 'RESSONÂNCIA MAGNÉTICA DE BACIA',
    ['Jejum de 4 horas quando contraste for utilizado',
     'Tempo de exame: 30–45 minutos',
     'Claustrofobia relevante — toda a pélvis dentro do imã',
     'Confirmar ausência de marca-passo, DIU de cobre é compatível',
     'Avaliar função renal se gadolínio será usado (NSF)',
     'Perguntar sobre próteses de quadril — materiais não ferromagnéticos são compatíveis',
     'Informar que bobina de superfície será posicionada sobre a pelve',
     'Homens: perguntar sobre prostatismo (indicação pode requerer protocolo prostático)'],
    ['Qual a indicação? (neoplasia, endometriose, prostatite, osteomielite, trauma?)',
     'Dor pélvica crônica ou aguda? Localização?',
     'Alterações do ciclo menstrual, sangramento anormal (mulheres)?',
     'Sintomas urinários ou intestinais associados?',
     'Febre, calafrios, suores noturnos (processo infeccioso/inflamatório)?',
     'Neoplasia conhecida em outra localização?',
     'Cirurgias pélvicas prévias?'],
    ['Neoplasias pélvicas — reto, bexiga, útero, ovário, próstata (estadiamento)',
     'Endometriose profunda — nódulos no septo reto-vaginal, ligamentos uterossacros, bexiga',
     'Osteomielite do sacro — edema medular, sequestro, fístulas',
     'Sacroileíte — bilateral, assimétrica, associada a espondiloartrites (HLA-B27)',
     'Cistos ovarianos — caracterização (dermoide, endometrioma, cisto funcional)',
     'Linfadenopatias pélvicas — localização, tamanho, extensão'],
    ['Bobina phased-array pélvica + bobina corporal',
     'Sequências: T1, T2 com e sem saturação de gordura, DWI (b=0,400,800)',
     'Contraste dinâmico com gadolínio para avaliação tumoral e endometrial',
     'Incluir do promontório sacral ao períneo',
     'Cortes axiais e coronais oblíquos (perpendicular ao eixo sacral)',
     'Gel vaginal ou retal como contraste negativo quando indicado'])

exams['braco'] = make_entry('braco', 'RESSONÂNCIA MAGNÉTICA DE BRAÇO',
    ['Não é necessário jejum',
     'Tempo de exame: 25–40 minutos por membro',
     'Claustrofobia geralmente mínima para membros',
     'Confirmar ausência de marca-passo ou dispositivos eletrônicos',
     'Avaliar função renal se contraste será usado (necessário para neoplasia/infecção)',
     'Perguntar sobre implantes ortopédicos (placas, parafusos, hastes) — podem causar artefactos',
     'Informar que o braço será posicionado ao lado do corpo ou acima da cabeça',
     'Orientar que não pode mover o braço durante as sequências'],
    ['Qual a indicação? (massa, trauma, infecção, neuropatia, tumor?)',
     'Tempo de evolução da lesão ou sintoma?',
     'Dor localizada ou irradiada? (pode indicar neuropatia ou processo infiltrativo)',
     'Febre, calor local, rubor? (sugere infecção ou abscesso)',
     'Neoplasia conhecida? (mama, pulmão — pode ser metástase)',
     'Déficit neurológico distal (força, sensibilidade)?',
     'Trauma recente ou antigo na região?'],
    ['Tumores de partes moles — lipoma, schwannoma, fibromatose, sarcoma (LMS, MPNST)',
     'Abscesso ou fasciíte necrosante — coleção com realce periférico, edema de partes moles',
     'Neuropatias — síndrome do túnel cárpico (antebraço/proximal), neurofibromatose',
     'Miosite ou polimiosite — edema intramuscular difuso, realce intersticial',
     'Metástases ósseas — lesões líticas ou blásticas no úmero',
     'Lesões vasculares — fístula arteriovenosa, pseudoaneurisma'],
    ['Bobina de superfície phased-array sobre o braço',
     'Sequências: T1, T2 SPAIR/STIR, difusão (DWI) para caracterização',
     'Contraste com gadolínio 0,1 mmol/kg para neoplasia, infecção e vascularização',
     'Incluir toda a extensão do úmero, do ombro ao cotovelo',
     'Cortes axiais e coronais, espessura 4–5mm com gap de 1mm',
     'Avaliar nervos periféricos quando neuropatia for a indicação'])

exams['colangio'] = make_entry('colangio', 'RESSONÂNCIA MAGNÉTICA DE COLANGIORM',
    ['Jejum de 4–6 horas antes do exame (melhora distensão de vias biliares)',
     'Tempo de exame: 30–45 minutos',
     'Claustrofobia — toda a região abdominal superior dentro do imã',
     'Confirmar ausência de marca-passo e avaliar função renal se gadolínio',
     'Perguntar sobre cirurgia biliodigestiva prévia (Billroth, hepaticoyeyunostomía)',
     'Orientar que contraste hepatobiliar (Eovist/Gd-EOB-DTPA) pode ser usado se disponível',
     'Não é necessário preparo com laxantes como na CPRE',
     'Informar que o exame pode incluir colangio e pancreatografia'],
    ['Qual a indicação? (icterícia, colelitíase, estenose biliar, tumor de pâncreas/VB?)',
     'Icterícia colestática ou hemolítica? (colúria, acolia presentes?)',
     'Dor abdominal tipo cólica biliar? (irradiação escapular)',
     'Episódios prévios de colangite ou pancreatitis biliar?',
     'Cirurgia biliar prévia? (colecistectomia, papilotomia)',
     'Neoplasia de pâncreas, via biliar ou vesícula conhecida?',
     'Colangiografia prévia (PTHC, CPRE) com stent biliar?'],
    ['Colelitíase — microlitíase intrahepática, barro biliar',
     'Estenoses biliares — benignas (pós-cirúrgicas, colangite esclerosante) vs. malignas (colangiocarcinoma)',
     'Dilatação de vias biliares — localização (hepático, colédoco), causa de obstrução',
     'Colangite esclerosante primária — estenoses multifocais, dilatações saculares ("beaded appearance")',
     'Tumor de vesícula — espessamento xantogranulomatoso vs. adenocarcinoma',
     'Vazamento biliar pós-cirúrgico — collections sub-hepáticos, biloma'],
    ['Bobina phased-array hepática + bobina corporal',
     'Sequências: T2 HASTE/coronal (colangiografia natural), T1 Dixon, difusão',
     'Contraste dinâmico com gadolínio: fase arterial, portal, hepática (equilibrada)',
     'Colangio-RM com sequências 3D T2SPACE/CUBE/Blade com MIP',
     'Avaliar ductos biliares intra e extra-hepáticos, vesícula, colédoco, ducto pancreático',
     'Se contraste hepatobiliar específico (EOB): adquirir fase hepatobiliar aos 20–45 min'])

exams['coluna_cervical'] = make_entry('coluna_cervical', 'RESSONÂNCIA MAGNÉTICA DE COLUNA CERVICAL',
    ['Não é necessário jejum',
     'Tempo de exame: 25–40 minutos',
     'Claustrofobia relevante — cabeça e pescoço dentro do imã',
     'Confirmar ausência de marca-passo (contraindicação absoluta), stents coronarianos geralmente compatíveis',
     'Avaliar função renal se contraste será usado (tumores, infecções)',
     'Informar que será necessário ficar imóvel e que o pescoço pode ficar levemente estendido',
     'Perguntar sobre trauma cervical recente — pode requerer RX antes para excluir fratura instável',
     'Implantes metálicos cervicais (placas, parafusos) — avaliar artefactos'],
    ['Qual a indicação? (hérnia discal, mielopatia, tumor, infecção, trauma?)',
     'Dor cervical com irradiação para membros superiores? (padrão radicular C5–T1)',
     'Déficit motor ou sensitivo nos membros?',
     'Disfunção de esfíncter vesical/anal? (sinal de alarme para mielopatia)',
     'Febre ou suspeita de infecção (espondilodiscite)?',
     'Neoplasia conhecida com risco de metástase?',
     'Histórico de artrite reumatoide ou espondiloartrite (risco de subluxação)?'],
    ['Hérnia discal cervical — C5–C6, C6–C7 mais comuns, compressão radicular ou medular',
     'Mielopatia compressiva — sinal intramedular em T2, espondilose com osteófitos posteriores',
     'Espondilolistese degenerativa — avaliação de olisthesis e canal medular',
     'Tumor intradural — meningioma, schwannoma, ependimoma (realce homogêneo vs. heterogêneo)',
     'Metástases vertebrais — lesão expansiva com destruição óssea, compressão medular',
     'Espondilodiscite — osteomielite, abscesso epidural, disco com hipersinal T2 e realce'],
    ['Bobina de crânio + neck-array coil',
     'Sequências: T1 sagital, T2 sagital (SPIR/SPAIR), T2* GRE (avaliar calcificação discal), DWI para tumor/infecção',
     'Contraste com gadolínio 0,1 mmol/kg para tumor, infecção, mielite',
     'Incluir de C1 a T1, com cobertura de junção crânio-cervical',
     'Cortes sagitais (3mm) e axiais (4mm) centrados nos discos e forames',
     'Avaliar medula espinhal, raízes, discos, forames neurais e corpos vertebrais'])

exams['coluna_lombar'] = make_entry('coluna_lombar', 'RESSONÂNCIA MAGNÉTICA DE COLUNA LOMBAR',
    ['Não é necessário jejum',
     'Tempo de exame: 20–35 minutos',
     'Claustrofobia geralmente moderada para esta região',
     'Confirmar ausência de marca-passo e avaliar função renal se contraste',
     'Informar que será necessário ficar em decúbito dorsal, pode haver leve desconforto',
     'Perguntar sobre próteses de quadril — artefactos metálicos podem prejudicar avaliação',
     'Claustrofobia pode requerer RM aberta para pacientes muito ansiosos',
     'Aplicar almofada sob os joelhos para conforto e redução da lordose'],
    ['Qual a indicação? (dor lombar, ciatalgia, estenose, avaliação pós-operatória?)',
     'Dor com irradiação para membros inferiores? (padrão radicular L4, L5, S1)',
     'Déficit motor, sensitivo ou alterações de esfíncter? (sinais de alarme)',
     'Histórico de cirurgia de coluna prévia? (qual nível, qual procedimento?)',
     'Febre, perda de peso ou dor noturna? (red flag para neoplasia/infecção)',
     'Atividade física ou trauma precipitante?',
     'Neoplasia conhecida em outra localização?'],
    ['Hérnia discal — protrusão/extrusão em L4–L5 e L5–S1, compressão radicular',
     'Estenose do canal vertebral — central e/ou foráminal, degenerativa ou congênita',
     'Espondilolistese — degenerativa ou ístmica, olisthesis vertebral, instabilidade',
     'Modic changes — Tipo I (edema/inflamação), Tipo II (gordura), Tipo III (esclerose)',
     'Cisto sinovial facetário — causa de estenose lateral e dor radicular',
     'Fratura de estresse — edema vertebral, comum em osteoporose ou esportistas',
     'Espondilodiscite / abscesso epidural — realce discal e de partes moles epidural',
     'Neoplasia — metástases, mieloma múltiplo ("punched out"), hemangioma agressivo'],
    ['Bobina de coluna lombar ou body-array coil',
     'Sequências: T1 sagital, T2 sagital (SPAIR), T2* GRE para discos degenerados, difusão (DWI) para fraturas e tumors',
     'Contraste com gadolínio 0,1 mmol/kg para infecção, tumor, cisto sinovial e pós-operatório',
     'Incluir de T11–L1 até o sacro; junção tóraco-lombar included for T12 fractures',
     'Cortes axiais (4mm) nos níveis de interesse (L3–L4, L4–L5, L5–S1)',
     'Avaliar: discos, forames neurais, articulações facetárias, medula (até cone medular em L1–L2)'])

exams['coluna_sacro'] = make_entry('coluna_sacro', 'RESSONÂNCIA MAGNÉTICA DE COLUNA SACRO-COCCÍGEA',
    ['Não é necessário jejum',
     'Tempo de exame: 25–35 minutos',
     'Claustrofobia geralmente leve para esta região inferior',
     'Confirmar ausência de marca-passo e avaliar função renal se contraste',
     'Perguntar sobre trauma na região sacral ou coccígea',
     'Informar que será posicionado em decúbito dorsal com bobina pélvica',
     'Cirurgias prévias nesta região (coccixectomía, curetagem sacral)?',
     'Considerar gel retal como contraste negativo para processo inflamatório'],
    ['Qual a indicação? (dor sacral, coccigodinia, tumor, fístula, infecção?)',
     'Dor em região sacral específica ou difusa?',
     'Irradiação para membros inferiores, região glútea ou perineal?',
     'Disfunção de esfíncter vesical/anal? (indica comprometimento de cone medular ou cauda equina)',
     'Febre, drenagem de secreção por região sacral? (fístula, abscesso)',
     'Neoplasia pélvica prévia? (cérvix, reto, próstata)',
     'Trauma recente ou antigo na região?'],
    ['Coccigodinia — edema do cóccix, subluxação, hipermobilidade',
     'Fratura de estresse sacral — edema bilateral ("Honda sign"), típico em osteoporose',
     'Tumor sacral — cordoma (mais comum), osteossarcoma, metástases, schwannoma',
     'Cisto sacro (cisto de Tarlov) — incidental, pode causar radiculopatia',
     'Sacroileíte — avaliar articulações sacroilíacas',
     'Fístula perianal / abscesso — avaliar com contraste e gel retal (protocolo esfíncter)',
     'Espondilodiscite — infecção do segmento sacro vertebral'],
    ['Bobina pélvica phased-array',
     'Sequências: T1 sagital e axial, T2 SPAIR/STIR sagital e axial, difusão',
     'Contraste com gadolínio 0,1 mmol/kg para tumor, infecção, fístula',
     'Gel retal (30–50ml) para avaliação de fístulas perianais quando pertinente',
     'Incluir de L4–L5 até o cóccix, com cobertura de articulações sacroilíacas',
     'Cortes axiais e coronais oblíquos, 4mm de espessura',
     'Avaliar medula espinhal baixa, cauda equina, raízes e osso sacral'])

exams['coluna_toracica'] = make_entry('coluna_toracica', 'RESSONÂNCIA MAGNÉTICA DE COLUNA TORÁCICA',
    ['Não é necessário jejum',
     'Tempo de exame: 30–45 minutos',
     'Claustrofobia relevante — toda a região torácica dentro do imã',
     'Confirmar ausência de marca-passo (avaliar tipo — MR-conditional podem existir)',
     'Avaliar função renal se contraste será usado',
     'Perguntar sobre implantes ortopédicos torácicos (instrumentação de Harrington, barras)',
     'Informar que será necessário controle respiratório (apneias curtas)',
     'Perguntar sobre prurido intenso nas costas (patologia a investigar)'],
    ['Qual a indicação? (deformidade, mielopatia, tumor, infecção, dor?)',
     'Dor torácica ou dorsal com padrão radicular (dor em faixa)?',
     'Déficit motor ou sensitivo nos membros inferiores?',
     'Disfunção esfincteriana vesical/anal?',
     'Febre persistente, sudorese noturna, perda de peso?',
     'Neoplasia conhecida (mama, pulmão — risco de metástase vertebral)?',
     'Escoliose ou deformidade torácica conhecida?'],
    ['Metástases vertebrais — compressão medular, destruição do corpo vertebral',
     'Mieloma múltiplo — lesões "punched out", compressão patológica',
     'Nódulos de Schmorl (hérnia intra-óssea) — comune, geralmente incidental',
     'Hemangioma vertebral — tipicamente T1/T2 hiperintenso, incidental',
     'Osteomielite / espondilodiscite — disco e vértebras com edema, realce, abscesso epidural',
     'Deformidade (escoliose, cifose) — avaliação rotacional dos corpos vertebrais',
     'Tumor intradural — meningioma (hiperintenso em T2), schwannoma, metástase leptomeníngea'],
    ['Bobina de superfície torácica ou body-array coil',
     'Sequências: T1 sagital, T2 SPIR/STIR sagital, DWI para tumor/infecção',
     'Contraste com gadolínio 0,1 mmol/kg para neoplasia e espondilodiscite',
     'Gating respiratório ou apneias para minimizar artefatos',
     'Incluir de C7 a L1, com cobertura completa da coluna torácica',
     'Cortes sagitais 3mm, axiais 4mm perpendiculares ao eixo vertebral',
     'Avaliar: medula espinhal torácica, discos, corpos vertebrais, costelas adjacentes'])

exams['cotovelo'] = make_entry('cotovelo', 'RESSONÂNCIA MAGNÉTICA DE COTOVELO',
    ['Não é necessário jejum',
     'Tempo de exame: 25–35 minutos',
     'Claustrofobia geralmente mínima para esta região',
     'Confirmar ausência de dispositivos metálicos na área',
     'Avaliar função renal se contraste será usado (necessário para neoplasia/infecção)',
     'Perguntar sobre implantes ortopédicos (placas, parafusos, próteses) — artefactos metálicos',
     'Informar que o cotovelo será posicionado ao lado do corpo ou acima da cabeça',
     'Orientar que não pode mover durante as sequências'],
    ['Qual a indicação? (trauma, epicondilite, síndrome do túnel cubital, massa?)',
     'Dor localizada ou irradiada? (padrão nervo ulnar, mediano ou radial)',
     'Tempo de evolução?',
     'Febre, calor, rubor local? (sugere infecção ou artrite séptica)',
     'Traumas prévios na região (fratura, luxação)?',
     'Neoplasia conhecida? (pode ser metástase)',
     'Limitação de movimento ou instabilidade articular?'],
    ['Epicondilite / epitrocleíte — tendinopatia dos extensores/flexores com edema intratendíneo',
     'Síndrome do túnel cubital — compressão do nervo ulnar no cotovelo',
     'Lesões da placa de crescimento — osteocondrite dissecante (OCD) do capítulo',
     'Fraturas ocultas — edema da medula óssea, linhas de fratura em T1/T2',
     'Artrite reumatoide — sinovite, erosões, derrame articular, PAN',
     'Tumores — lipoma, schwannoma do nervo ulnar, osteossarcoma'],
    ['Bobina de superfície phased-array para cotovelo',
     'Sequências: T1 axial, T2 SPAIR/STIR coronal e axial, GRE para cartilagem, difusão',
