exams['cotovelo'] = make_entry('cotovelo', 'RESSONÂNCIA MAGNÉTICA DE COTOVELO',
    ['Não é necessário jejum',
     'Tempo de exame: 25–35 minutos',
     'Claustrofobia geralmente mínima para esta região',
     'Confirmar ausência de dispositivos metálicos na área',
     'Avaliar função renal se contraste será usado (necessário para neoplasia/infecção)',
     'Perguntar sobre implantes ortopédicos (placas, parafusos, próteses) — artefactos metálicos',
     'Informar que o cotovelo será posicionado ao lado do corpo ou acima da cabeça',
     'Orientar que não pode mover durante as sequências'],
    ['Qual a indicação? (trauma, epicondilite, síndrome do túnel cubital, massa?)',
     'Dor localizada ou irradiada? (padrão nervo ulnar, mediano ou radial)',
     'Tempo de evolução?',
     'Febre, calor, rubor local? (sugere infecção ou artrite séptica)',
     'Traumas prévios na região (fratura, luxação)?',
     'Neoplasia conhecida? (pode ser metástase)',
     'Limitação de movimento ou instabilidade articular?'],
    ['Epicondilite / epitrocleíte — tendinopatia dos extensores/flexores com edema intratendíneo',
     'Síndrome do túnel cubital — compressão do nervo ulnar no cotovelo',
     'Lesões da placa de crescimento — osteocondrite dissecante (OCD) do capítulo',
     'Fraturas ocultas — edema da medula óssea, linhas de fratura em T1/T2',
     'Artrite reumatoide — sinovite, erosões, derrame articular',
     'Tumores — lipoma, schwannoma do nervo ulnar, osteossarcoma'],
    ['Bobina de superfície phased-array para cotovelo',
     'Sequências: T1 axial, T2 SPAIR/STIR coronal e axial, GRE para cartilagem, difusão',
     'Contraste com gadolínio 0,1 mmol/kg para tumor, infecção, sinovite',
     'Posicionamento em flexão de 90 graus quando possível',
     'Cortes axiais e coronais, espessura 3mm, FOV pequeno (10–12cm)',
     'Avaliar: úmero distal, rádio e ulna proximais, complexo ligamentar colateral, nervos'])

exams['coxa'] = make_entry('coxa', 'RESSONÂNCIA MAGNÉTICA DE COXA',
    ['Não é necessário jejum',
     'Tempo de exame: 25–40 minutos',
     'Claustrofobia geralmente mínima para membros inferiores',
     'Confirmar ausência de dispositivos eletrônicos implantados',
     'Avaliar função renal se contraste será usado (necessário para neoplasia/infecção)',
     'Perguntar sobre implantes ortopédicos (hastes, placas) na coxa',
     'Informar que a coxa será posicionada em ligera rotação externa',
     'Orientar que não pode mover durante as sequências'],
    ['Qual a indicação? (massa, dor, trauma, infecção, tumor?)',
     'Tempo de evolução da massa ou sintoma?',
     'Dor localizada ou difusa na coxa? (pode indicar miosite, rabdomiólise)',
     'Febre, calafrios? (sugere infecção ou abscesso)',
     'Neoplasia conhecida (próstata, mama, pulmão — metástase)?',
     'Trauma recente ou antigo na região?',
     'Fraqueza muscular localizada?'],
    ['Tumores de partes moles — lipoma, fibroma, sarcoma (LMS, Lipossarcoma, MPNST)',
     'Abscesso intramuscular — coleção com realce em anel, edema de tecidos circunjacentes',
     'Miosite ossificante — calcificação de partes moles, edema muscular',
     'Metástases femorais — lesões líticas ou blásticas',
     'Lesões musculares — strain, tear parcial/completo, cicatriz fibrosa',
     'Neuropatia — compressão do nervo ciático (geralmente por massas glúteas)'],
    ['Bobina de superfície phased-array grande sobre a coxa',
     'Sequências: T1, T2 SPAIR/STIR, difusão (DWI) para caracterização',
     'Contraste com gadolínio 0,1 mmol/kg para neoplasia, infecção',
     'Incluir toda a extensão do fêmur (do quadril ao joelho)',
     'Cortes axiais e coronais, espessura 5mm com gap',
     'Avaliar: fêmur, músculos (quadríceps, adutores, isquiotibiais), nervo ciático, vascular'])

exams['joelho'] = make_entry('joelho', 'RESSONÂNCIA MAGNÉTICA DE JOELHO',
    ['Não é necessário jejum',
     'Tempo de exame: 25–40 minutos',
     'Claustrofobia geralmente mínima para esta região',
     'Confirmar ausência de implantes metálicos (próteses, parafusos) — artefactos',
     'Avaliar função renal se contraste será usado (tumores, infecções)',
     'Informar que o joelho será posicionado em ligera flexão (10–15 graus)',
     'Perguntar sobre lesões prévias, cirurgias ou artroscopia',
     'Roupas sem elementos metálicos na região inferior'],
    ['Qual a indicação? (trauma, dor, instabilidade, tumor, infecção?)',
     'Mecanismo do trauma (torção, impacto direto, hiperextensão)?',
     'Bloqueio articular, falsejo ou instabilidade?',
     'Derrame articular palpável?',
     'Dor em linha articular medial ou lateral, ou retropatelar?',
     'Histórico de ligamentoplastia ou meniscectomia prévia?',
     'Sintomas de bloqueio mecânico vs. dor inflamatória?'],
    ['Lesões meniscais — lágrima horizontal, vertical, radial, em alça de balde (root tear)',
     'Lesões ligamentares — LCA (mais comum), LCP, LCM, LLI',
     'Lesões condrais — classificação de Outerbridge, osteocondrite dissecante (OCD)',
     'Cisto de Baker — coleção poplítea, comunicar com articulação',
     'Gonartrose — osteófitos, edema subcondral (Modic-like), pinçamento articular',
     'Tumores — osteossarcoma, condroblastoma, tumor de células gigantes (TCG)'],
    ['Bobina de joelho dedicada ou bobina de superfície phased-array',
     'Sequências: PD FS e T2 FS (sagital e coronal) para meniscos e ligamentos',
     'T1 sagital e coronal para anatomia óssea e gordura',
     'GRE (gradient echo) 3D para cartilagem (MapChange ou VIBE)',
     'Contraste com gadolínio 0,1 mmol/kg para tumores, infecções, sinovite',
     'DWI para caracterização de lesões tumorais e infecção',
     'Posicionamento: ligera flexão 10–15 graus, pé em rotação externa',
     'Cortes: sagital 4mm, coronal 3mm, axial 4mm quando necessário'])

exams['mamas'] = make_entry('mamas', 'RESSONÂNCIA MAGNÉTICA DE MAMAS',
    ['Marcar entre dia 7 e 14 do ciclo menstrual (fase proliferativa) para reduzir contraste de fundo (ACR)',
     'Não é necessário jejum',
     'Tempo de exame: 20–35 minutos mais mamografia convencional se simultânea',
     'Claustrofobia — toda a região torácica anterior dentro do imã',
     'Confirmar ausência de marca-passo e avaliar função renal se gadolínio',
     'Trazer mamografias e ultrassonografias anteriores para comparação',
     'Perguntar sobre antecedentes de neoplasia de mama e status de BRCA',
     'Implantes mamários — informar tipo (salineira vs. silicone) para protocolo',
     'Confirmar ausência de gestação (contraindicação relativa no 1º trimestre)'],
    ['Qual a indicação? (rastreio em alto risco, estadiamento, avaliação de resposta neoadjuvante?)',
     'Data da última mamografia e resultado?',
     'Mutação de BRCA1/BRCA2 conhecida?',
     'Histórico pessoal de neoplasia de mama ou ovário?',
     'Terapia hormonal atual ou prévia (TRH)?',
     'Status menopausal?',
     'Implantes mamários — tempo de colocação, tipo, ruptura prévia?'],
    ['Neoplasia de mama — carcinoma ductal invasivo (CDI), carcinoma lobular invasivo (CLI)',
     'Lesões precursoras — LCIS, DCIS de alto grau (não calcificadas na RM)',
     'Implantes mamários — ruptura intracapsular ou extracapsular, contractura',
     'Resposta ao tratamento neoadjuvante — redução do tamanho, mudança de cinética',
     'Lesões occultas na mamografia — lesões apenas visíveis em RM',
     'Linfonodos axilares — avaliação de comprometimento metastático'],
    ['Bobina de mama dedicada (biomarray) em posição prona',
     'Sequências: T2 SPAIR/STIR (avaliar edema, implantes), T1 pré-contraste',
     'Contraste dinâmico: gadolínio 0,1 mmol/kg, séries multiphase (pré, pós 1min, 2min, 3min, 4min)',
     'Subtração de imagens para evaluar realce',
     'Avaliação de cinética de realce (Kaiser Score ou BI-RADS)',
     'DWI (b=0,750) para caracterização adicional',
     'Cortes: axial 2–3mm, coronal ou sagittal quando necessário',
     'Incluir cadeia axilar e mamária interna se indicada'])

exams['mao'] = make_entry('mao', 'RESSONÂNCIA MAGNÉTICA DE MÃO',
    ['Não é necessário jejum',
     'Tempo de exame: 20–30 minutos',
     'Claustrofobia geralmente mínima para esta região',
     'Confirmar ausência de fragmentos metálicos intraorais (relevante se mão dominante)',
     'Avaliar função renal se contraste será usado (necessário para neoplasia/infecção)',
     'Perguntar sobre dor específica — qual dedo, qual articulação (IFD, IFP, MCF)?',
     'Informar que a mão será posicionada ao lado do corpo com dedos em extensão',
     'Dispositivos ortodônticos — geralmente não afetam a mão'],
    ['Qual a indicação? (trauma, artrite, tumor, síndrome do túnel do carpo?)',
     'Dor articular específica ou difusa?',
     'Rigidez matinal? (sugere processo inflamatório)',
     'Tumefação articular, calor local?',
     'Deformidade articular conhecida (artrite reumatoide, psoríase)?',
     'Trauma recente ou antigo?',
     'Neoplasia conhecida?'],
    ['Artrite reumatoide — sinovite, erosões marginais, osteopenia adjacente, desvios ulnaires',
     'Artropatia psoriásica — dactilite ("dedo em salsicha"), erosões, neoformação óssea',
     'Lesões ligamentares — ligamentos colaterais das articulações IFD/IFP/MCF',
     'Tendinopatias — tendinose, tenossinovite (dedo em gatilho)',
     'Cisto sinovial (ganglion cyst) — lesão quística adjacente à articulação',
     'Tumores — encondroma, osteossarcoma, tumor de células gigantes (TCG)'],
    ['Bobina de mão dedicada ou bobina de superfície pequena',
     'Sequências: T1, T2 SPAIR/STIR, GRE 3D para cartilagem',
     'Contraste com gadolínio 0,1 mmol/kg para sinovite, tumor, infecção',
     'Posicionamento: mão em posição neutra ou ligeira flexão',
     'FOV pequeno (6–8cm), cortes finos 2–3mm, matriz alta',
     'Cortes axiais e coronais, evaluar todas as articulações dos dedos',
     'Incluir tendões flexores e extensores, ligamentos colaterais'])

exams['ombro'] = make_entry('ombro', 'RESSONÂNCIA MAGNÉTICA DE OMBRO',
    ['Não é necessário jejum',
     'Tempo de exame: 25–35 minutos',
     'Claustrofobia geralmente leve — apenas o ombro dentro do imã',
     'Confirmar ausência de prótese de ombro (implantes metálicos provocam artefactos)',
     'Avaliar função renal se contraste será usado (necessário para tumor, infecção, ARTRO-RM)',
     'Perguntar sobre instabilidade recidivante ou episódios de luxação prévios',
     'Informar que o ombro será em rotação neutra ou externa dependendo do protocolo',
     'Perguntar sobre cirurgia prévia (Bankart, reparo do manguito rotador)'],
    ['Qual a indicação? (manguito rotador, instabilidade, conflito subacromial, ARTRO-RM?)',
     'Dor anterior ou lateral do ombro? Piora à noite?',
     'Fraqueza para elevar o braço acima da cabeça?',
     'Episódios de luxação ou subluxação?',
     'História de trauma (luxação traumática, fratura)?',
     'Limitação de rotação externa ou interna?',
     'Trabalhos de risco para conflito subacromial (pintores, encanadores)?'],
    ['Lesões do manguito rotador — tendinopatia, tears parciais e completos (supraespinhal, infraespinhal)',
     'Conflito subacromial/subcoracoide — bursite subacromial, osteófitos do acrômio',
     'Lesão de Bankart — lesão do lábio glenoidal ântero-inferior (instabilidade)',
     'Lesão de Hill-Sachs — indentação do úmero posterior por luxação anterior',
     'Capsulite adesiva ("ombro congelado") — espessamento capsular, hipointenso em T2',
     'Tendinopatia calcária — deposição de cálcio no supraespinhal, hipointenso em todas as sequências'],
    ['Bobina de ombro dedicada ou shoulder-array coil',
     'Sequências: ABDução-RoTAÇÃO externa (ABER) para Bankart, T1/T2 para osso',
     'T2 SPAIR/STIR sagital, coronal e axial para manguito e lábio',
     'ARTRO-RM com gadolínio diluído intra-articular (0,5ml gadolínio + 20ml soro) se indicada',
     'Contraste IV com gadolínio 0,1 mmol/kg para tumor, infecção, ARTRO-RM',
     'Posicionamento: rotação neutra ou externa quando possível',
     'Cortes axiais e coronais 3–4mm oblíquos ao eixo da escápula'])

exams['orbitas'] = make_entry('orbitas', 'RESSONÂNCIA MAGNÉTICA DE ÓRBITAS',
    ['Não é necessário jejum',
     'Tempo de exame: 25–35 minutos',
     'Claustrofobia relevante — toda a cabeça dentro do imã',
     'Confirmar ausência de fragmentos metálicos intraorbitários (corpo estranho — contraindicação)',
     'Implantes oculares (próteses) — geralmente compatíveis, mas verificar',
     'Avaliar função renal se gadolínio será usado',
     'Informar que deve manter os olhos fechados e imóveis durante o exame',
     'Perguntar sobre doença de Graves ou outros distúrbios tireoidianos',
     'Alertar que o equipamento gera ruído — não se assustar'],
    ['Qual a indicação? (neuropatia óptica, tumor, inflamação, trauma?)',
     'Perda de acuidade visual súbita ou gradual?',
     'Dor ocular com movimentos?',
     'Diplopia (visão dupla)? Qual padrão (horizontal, vertical)?',
     'Proptose (olho saltado) — unilateral ou bilateral?',
     'Doença de Basedow-Graves conhecida?',
     'Histórico de neoplasia sistêmica (risco de metástase)?'],
    ['Neuropatia óptica inflamatória — realce do nervo óptico, esclerose múltipla',
     'Orbitopatia de Graves — proptose, hipertrofia dos músculos extraoculares, realce',
     'Glioma do nervo óptico — expansão do nervo, hipointenso em T1, realce',
     'Meningioma de nervo óptico — realce meníngeo, "tram track sign"',
     'Massas orbitárias — cavernoma (realce tardio), linfangioma, hemangioma',
     'Celulite orbital — edema orbitário, realce de partes moles, gordura preservada na preseptal'],
    ['Bobina de crânio ou bobina de órbita dedicada',
     'Sequências: T1 fat-sat coronal, T2 FAT-SAT coronal e axial, FLAIR',
     'DWI para caracterização de lesões (restrição no glioma, retinoblastoma)',
     'Contraste com gadolínio 0,1 mmol/kg para tumor, inflamação, neuropatia óptica',
     'Cortes coronais finos (2–3mm) perpendiculares ao nervo óptico',
     'Incluir nervo óptico completo (do disco ao quiasma)',
     'Avaliar: globo ocular, músculos extraoculares, nervo óptico, glândula lacrimal, gordura orbitária'])

exams['ossos_temporais'] = make_entry('ossos_temporais', 'RESSONÂNCIA MAGNÉTICA DE OSSOS TEMPORAIS',
    ['Não é necessário jejum',
     'Tempo de exame: 30–45 minutos (bilateral)',
     'Claustrofobia relevante — a cabeça fica dentro do imã',
     'Confirmar ausência de implantes cocleares não compatíveis com RM (verificar tipo)',
     'Avaliar função renal se gadolínio será usado (NSF)',
     'Perguntar sobre zumbido, hipoacusia, vertigem — indicar protocolo específico',
     'Informar que deve ficar imóvel e que haverá ruído intenso',
     'Dispositivos auditivos — remover antes do exame'],
    ['Qual a indicação? (hipoacusia, colesteatoma, tumor, vertigem, neuralgia?)',
     'Hipoacusia — unilateral ou bilateral? Condutiva ou neurossensorial?',
     'Zumbido (tinnitus) — pulsátil ou contínuo?',
     'Episódios de vertigem posicional (VPPB) ou de Ménière?',
     'Paralisia facial periférica — House-Brackmann grau?',
     'Otalgia com otorrea (secreção)?',
     'Cirurgias otológicas prévias?'],
    ['Colesteatoma — massa em T1 intermediário, T2 hiperintenso, realce perilinfático, erosão de osso',
     'Neuroma do acústico (schwannoma vestibular) — massa no ângulo pontocerebelar, realce intenso',
     'Malformação de Mondini — aplasia de turns do caracol, alterações vestibulares',
     'Labirintite — realce do labirinto membranoso na concentração',
     'Glomus tympanicum — massa no ouvido médio, realce vascular',
     'Fístula perilinfática — não visível diretamente em RM, diagnóstico clínico'],
    ['Bobina de crânio ou bobina de osso temporal dedicada',
     'Sequências: T1, T2 SPACE/CUBE (3D), DWI para colesteatoma vs. mucosa',
     'FIESTA/CISS para anatomia fina dos ossículos e nervos',
     'Contraste com gadolínio 0,1 mmol/kg para tumor, inflamação, colesteatoma',
     'Incluir ouvidos bilateralmente, ângulos pontocerebelares, condutos auditivos internos',
     'Cortes axiais e coronais 1–2mm de espessura, alta resolução',
     'Avaliar: cóclea, vestíbulo, canais semicirculares, nervos facial e vestibulococlear'])

exams['pe'] = make_entry('pe', 'RESSONÂNCIA MAGNÉTICA DE PÉ',
    ['Não é necessário jejum',
     'Tempo de exame: 25–35 minutos',
     'Claustrofobia geralmente mínima para esta região',
     'Confirmar ausência de implantes metálicos no pé/tornozelo',
     'Avaliar função renal se contraste será usado (necessário para neoplasia/infecção)',
     'Perguntar sobre arco plantar doloroso ou neuroma de Morton',
     'Informar que o pé será posicionado em carga parcial ou não conforme protocolo',
     'Orientar que deve permanecer imóvel durante o exame'],
    ['Qual a indicação? (trauma, artrite, tumor, neuroma, fasciíte?)',
     'Dor em arco plantar, retropé ou antepé?',
     'Fasciíte plantar — dor no calcâneo de manhã ao levantar?',
     'Neuroma de Morton — dor entre terceiros e quartos dedos?',
     'Deformidade (joanete, pé plano/cavo)?',
     'Trauma ou fratura por estresse?',
     'Artrite inflamatória (espondiloartrite)?'],
    ['Fasciíte plantar — espessamento do plantar fascia (≥4mm), edema do calcâneo adjacente',
     'Neuroma de Morton — espessamento do nervo interdigital, hipointenso em T1/T2, realce',
     'Hallux rigidus — osteófitos, irregularidade da 1ª articulação MTP, edema subcondral',
     'Tendinopatia do tibial posterior — disfunção do arco longitudinal, tenossinovite',
     'Artropatia inflamatória — psoríase, espondiloartrite (entesite do Aquiles)',
     'Tumores — osteossarcoma, encondroma, tumor de células gigantes (TCG) do tarso'],
    ['Bobina de pé/tornozelo dedicada ou bobina de superfície pequena',
     'Sequências: T1, T2 SPAIR/STIR sagital e coronal, difusão',
     'Contraste com gadolínio 0,1 mmol/kg para tumor, infecção, neuroma',
     'FOV pequeno (10–12cm), cortes 3mm, matriz alta',
     'Incluir: tarso, metatarso, falanges, articulações, tendões, ligamentos',
     'Cortes axiais e coronais, avaliação de arco plantar e retropé'])

exams['pescoco'] = make_entry('pescoco', 'RESSONÂNCIA MAGNÉTICA DE PESCOÇO',
    ['Não é necessário jejum',
     'Tempo de exame: 30–40 minutos',
     'Claustrofobia relevante — cabeça e pescoço dentro do imã',
     'Confirmar ausência de implantes metálicos cervicais ou marca-passo',
     'Avaliar função renal se gadolínio será usado (tumores, infecções)',
     'Informar que deve evitar deglutir durante as sequências (minimiza artefactos)',
     'Perguntar sobre nódulos tireoidianos conhecidos, história de CA de tireoide',
     'Retirar joias e acessórios metálicos do pescoço e cabeça'],
    ['Qual a indicação? (nódulo tireoidiano, massa cervical, estadiamento de CA?)',
     'Rouquidão persistente, disfagia, odinofagia?',
     'Nódulo cervical palpável — localização, tempo de evolução?',
     'Neoplasia de cabeça e pescoço conhecida (laringe, faringe, tireoide)?',
     'Fumo, etilismo (fatores de risco para carcinoma escamoso)?',
     'Febre, dor cervical — pode indicar processo inflamatório/infeccioso?',
     'Linfonodomegalia cervical — quando foi notada?'],
    ['Neoplasias de tireoide — nódulos Bosniak-like, carcinoma papilar (microcalcificações)',
     'Carcinoma de laringe/faringe — espessamento mucosal, invasão de cartilagens',
     'Linfonodomegalias metastáticas — perda do hilo gorduroso, necrose central, realce',
     'Processos inflamatórios — adenite, abscesso cervical, linfadenite tuberculosa',
     'Paratireoide — adenoma de paratireoide (hipersinal em T2, realce)',
     'Lesões de glândulas salivares — tumor misto (pleomorphic adenoma), carcinoma'],
    ['Bobina de pescoço (neck-array) + bobina de crânio',
     'Sequências: T1, T2 SPAIR/STIR, difusão (DWI) para caracterização e adenopatia',
     'Contraste com gadolínio 0,1 mmol/kg para tumores, infecções, adenopatia',
     'Incluir de base do crânio (clivus) até o arco aórtico (para cadeias cervicais)',
     'Cortes axiais 4–5mm do hioide ao arco aórtico',
     'Avaliar: tireoide, paratireoides, laringe, faringe, glândulas salivares, linfonodos'])

exams['punho'] = make_entry('punho', 'RESSONÂNCIA MAGNÉTICA DE PUNHO',
    ['Não é necessário jejum',
     'Tempo de exame: 20–30 minutos',
     'Claustrofobia geralmente mínima para esta região',
     'Confirmar ausência de fragmentos metálicos intraorais ou na mão',
     'Avaliar função renal se contraste será usado (necessário para neoplasia/infecção)',
     'Perguntar sobre dor específica — síndrome do túnel do carpo, trauma, artrite?',
     'Informar que o punho será posicionado ao lado do corpo',
     'Dispositivos ortodônticos — geralmente não afetam o punho'],
    ['Qual a indicação? (síndrome do túnel do carpo, trauma, tumor, artrite?)',
     'Dormência ou formigamento nos dedos (polegar, indicador, médio)?',
     'Dor no punho — dorsal, volar, ou ulnar?',
     'Fraqueza na preensão?',
     'Trauma ou fratura de Colles/Smith prévia?',
     'Atividades repetitivas (informatos, músicos)?',
     'Artrite reumatoide ou outras condições inflamatórias?'],
    ['Síndrome do túnel do carpo — compressão do nervo mediano, avaliar nervo e tendões',
     'Lesões do fibrocartilagem triangular (FCT) — lágrimas do complexo triangular',
     'Tendinopatias — tendinose de extensores ou flexores, tenossinovite',
     'Cistos sinoviais (ganglion) — lesões quísticas dorsais ou volares do punho',
     'Fraturas occultas — edema da medula óssea dos ossos do carpo (escafoide)',
     'Doença de Kienböck — necrose avascular do semilunar, hipossinal em T1'],
    ['Bobina de punho dedicada ou bobina de superfície pequena',
     'Sequências: T1, T2 SPAIR/STIR coronal e axial, GRE 3D para FCT',
     'Contraste com gadolínio 0,1 mmol/kg para tumor, infecção, sinovite',
     'FOV pequeno (8–10cm), cortes 2–3mm, matriz alta',
     'Incluir: rádio e ulna distais, ossos do carpo, articulações radio-cárpica e úlno-cárpica',
     'Cortes coronais e axiais, avaliação do túnel do carpo e nervo mediano'])

exams['quadril'] = make_entry('quadril', 'RESSONÂNCIA MAGNÉTICA DE QUADRIL',
    ['Não é necessário jejum',
     'Tempo de exame: 25–40 minutos',
     'Claustrofobia moderada — pelve e quadril dentro do imã',
     'Confirmar ausência de prótese de quadril (contraindicação absoluta se ferromagnética)',
     'Avaliar função renal se contraste será usado (necessário para neoplasia/infecção, ARTRO-RM)',
     'Perguntar sobre dor específica — anterior (inguinal), lateral, posterior (glútea)',
     'Informar que o quadril será em rotación interna e abdução quando possível',
     'Orientar que deve permanecer imóvel durante o exame'],
    ['Qual a indicação? (osteonecrose, impacto femoroacetabular, artrite, tumor?)',
     'Dor anterior do quadril (virilha) — padrão de impacto femoroacetabular (FAI)?',
     'Dor lateral — bursite trocantérica?',
     'Dor posterior — síndrome do piriforme, dor sacroilíaca referred?',
     'Limitação de rotação interna do quadril?',
     'Histórico de uso prolongado de corticoides (risco de osteonecrose)?',
     'Quadril em botoeira ou claudicação?'],
    ['Impacto femoroacetabular (FAI) — Pincer (acetábulo sobrecoberto) ou Cam (côndilo deformado)',
     'Lesão do lábio acetabular — tear do labrum, geralmente ântero-superior',
     'Osteonecrose da cabeça femoral — necrose avascular, sinal em duplo contorno em T1',
     'Bursite trocantérica — líquido na bolsa do grande trocânter',
     'Tendinopatia dos músculos do quadril — glúteo médio, mínimo, piriforme',
     'Tumores — osteossarcoma, condrossarcoma, metástases, sarcoma de Ewing'],
    ['Bobina body-array ou surface coil sobre o quadril',
     'Sequências: T1 e T2 SPAIR/STIR coronal e axial, GRE 3D para labrum',
     'ARTRO-RM com gadolínio diluído intra-articular se indicada',
     'Contraste IV com gadolínio 0,1 mmol/kg para tumor, infecção, bursite',
     'Incluir quadril e região do grande trocânter',
     'Posicionamento: ligera rotación interna do quadril (15–20 graus)',
     'FOV: 18–22cm, cortes 3–4mm, alta resolução'])

exams['regiao_escapular'] = make_entry('regiao_escapular', 'RESSONÂNCIA MAGNÉTICA DE REGIÃO ESCAPULAR',
    ['Não é necessário jejum',
     'Tempo de exame: 30–40 minutos',
     'Claustrofobia moderada — região escapular e ombro dentro do imã',
     'Confirmar ausência de implantes metálicos (placas, parafusos, hastes)',
     'Avaliar função renal se contraste será usado (necessário para neoplasia/infecção)',
     'Perguntar sobre vigilância após cirurgia de mama (reconstrução com retalhos)?',
     'Informar que o braço será posicionado de forma confortável para evitar movimento',
     'Orientar uso de roupas sem elementos metálicos no tronco'],
    ['Qual a indicação? (tumor escapular, massa de partes moles, infecção?)',
     'Massa palpável na região escapular — tempo de evolução?',
     'Dor na região escapular ou escapulo-torácica?',
     'Neoplasia de mama tratada com reconstrução (retalho musculocutâneo)?',
     'Infiltração de parts moles após biópsia?',
     'Febre, calafrios — processo infeccioso/inflamatório?',
     'Histórico de trauma ou cirurgia prévia na região?'],
    ['Tumores escapulares — osteossarcoma, metástases, mieloma, tumor de Ewing',
     'Lesões de partes moles — lipoma, sarcoma, fibromatose, tumor desmoide',
     'Infecções — osteomielite da escápula, abscesso de parts moles',
     'Avaliação de retalhos cirúrgicos — viabilidade do retalho musculocutâneo',
     'Bursite subescapular — collections fluideiras na fossa subescapular',
     'Lesões infiltrativas — síndrome de Pancoast (tumor do ápice pulmonar)'],
    ['Bobina de superfície phased-array grande sobre a região escapular',
     'Sequências: T1, T2 SPAIR/STIR, difusão (DWI) para caracterização',
     'Contraste com gadolínio 0,1 mmol/kg para tumor, infecção, avaliação de retalho',
     'Incluir toda a escápula, região supra e infraclavicular',
     'Cortes axiais e coronais 4–5mm, FOV amplo para avaliar parede torácica',
     'Avaliar: osso escapular, músculos periescapulares, pleura, cadeia axilar'])

exams['sela_turcica'] = make_entry('sela_turcica', 'RESSONÂNCIA MAGNÉTICA DE SELA TURCICA',
    ['Não é necessário jejum',
     'Tempo de exame: 25–35 minutos',
     'Claustrofobia relevante — a cabeça fica dentro do imã',
     'Confirmar ausência de implantes metálicos intracranianos',
     'Avaliar função renal se gadolínio será usado',
     'Informar que o exame inclui avaliação da hipófise e do quiasma óptico',
     'Perguntar sobre alterações visuais ou distúrbios hormonais conhecidos',
     'Dispositivos auditivos — remover antes do exame'],
    ['Qual a indicação? (adenoma hipofisário, craniofaringioma, diabetes insipidus?)',
     'Alterações visuais — perda de campo visual (bitemporal), diplopia?',
     'Distúrbios hormonais — galactorréia, amenorréia, gigantismo/acromegalia?',
     'Cefaleia persistente ou atípica?',
     'Polyúria, polidipsia (diabetes insipidus)?',
     'Macroprolactinoma conhecido? (avaliando efeito de medicação)',
     'Cirurgias hipofisárias prévias?'],
    ['Adenoma hipofisário — micro (<10mm) vs. macro (≥10mm),侵襲性 vs. não-invasivo',
     'Craniofaringioma — cystic component, calcificação,儿童 e adultos',
     'Prolactinoma — mais comum, avaliar resposta ao análogo de dopamina',
     'Meningioma do tubérculo selar — realce homogêneo, dural tail',
     'Hipofisite linfocítica — realce difuso da hipófise, pós-parto',
     'Aneurisma da artéria carótida intracavernosa — causa de mass effect'],
    ['Bobina de crânio phased-array',
     'Sequências: T1 sagital e coronal, T2 coronal, FLAIR',
     'Contraste dinâmico com gadolínio 0,1 mmol/kg — fases Dinâmicas para microadenomas',
     'DWI para diferenciação de cistos (craniofaringioma vs. cisto aracnóideo)',
     'Cortes coronais e sagitais 2–3mm através da hipófise',
     'Incluir: hipófise, quiasma óptico, seio cavernoso, hipotálamo',
     'Avaliar relação com carótidas internas e nervos oculomotores (III, IV, V1, VI)'])

exams['tornozelo'] = make_entry('tornozelo', 'RESSONÂNCIA MAGNÉTICA DE TORNOZELO',
    ['Não é necessário jejum',
     'Tempo de exame: 25–35 minutos',
     'Claustrofobia geralmente mínima para esta região',
     'Confirmar ausência de implantes metálicos (parafusos de hastes, placas)',
     'Avaliar função renal se contraste será usado (necessário para neoplasia/infecção)',
     'Perguntar sobre instabilidade recidivante ou lesões ligamentares prévias',
     'Informar que o tornozelo será posicionado em flexão plantar de 20 graus',
     'Orientar que deve permanecer imóvel durante o exame'],
    ['Qual a indicação? (trauma, instabilidade, tendonopatia, tumor, ARTRO-RM?)',
     'Entorse de tornozelo — mecanismo (inversão vs. eversão)?',
     'Instabilidade crónica — episódios de "falsejo" ou torção?',
     'Dor em qual região? (anterolateral, medial, posterior, Maleolo?)',
     'Lesões prévias de ligamentos (ATFL, CFL, PTFL)?',
     'Tendinopatia de Aquiles ou tibial posterior